Added Notification capability for TODOItem.
Nearsoft/android-school pull request #20
Opened 2017-03-03 22:23 UTC by Mathreyu

- This includes a notification that goes of 10 secs after.
- Switch that turns notification on.

2017-03-03 22:48 UTC, RoyMontoya requested changes

2017-03-03 22:48 UTC, RoyMontoya commented on todoapp/TODOapp/app/src/main/java/com/nearsoft/androidschool/todoapp/activities/notification/NotificationPublisher.java
> +        Notification notification = intent.getParcelableExtra("notification");
use a string constant here NOTIFICATION_EXTRA = "notification", instead of hardcoded string

2017-03-03 22:48 UTC, RoyMontoya commented on todoapp/TODOapp/app/src/main/java/com/nearsoft/androidschool/todoapp/activities/notification/NotificationPublisher.java
> +        int id = intent.getIntExtra("notification-id", 0);
same here use a constant here ID_NOTIFICATION_EXTRA = "notification-id" , instead of hardcoded string

2017-03-03 22:48 UTC, RoyMontoya commented on todoapp/TODOapp/app/src/main/java/com/nearsoft/androidschool/todoapp/activities/detail/DetailActivity.java
> +        notificationIntent.putExtra("notification id", 1);
do not use hardcoded string, use a string constant here NOTIFICATION_EXTRA = "notification"

2017-03-03 22:48 UTC, RoyMontoya commented on todoapp/TODOapp/app/src/main/java/com/nearsoft/androidschool/todoapp/activities/detail/DetailActivity.java
> +        notificationIntent.putExtra("notification", notification);
do not use hardcoded string, use a string constant here ID_NOTIFICATION_EXTRA = "notification-id"

2017-03-03 22:53 UTC, jmsalcido commented
👍

2017-03-03 22:53 UTC, jmsalcido approved these changes
👍

2017-03-04 01:46 UTC, Mathreyu commented on todoapp/TODOapp/app/src/main/java/com/nearsoft/androidschool/todoapp/activities/notification/NotificationPublisher.java
> +        Notification notification = intent.getParcelableExtra("notification");
I don't really see the relevance on changing these, given that there are not many classes that access them.

2017-03-04 02:09 UTC, jmsalcido commented on todoapp/TODOapp/app/src/main/java/com/nearsoft/androidschool/todoapp/activities/notification/NotificationPublisher.java
> +        Notification notification = intent.getParcelableExtra("notification");
nah just do it.

2017-03-04 02:16 UTC, Mathreyu commented on todoapp/TODOapp/app/src/main/java/com/nearsoft/androidschool/todoapp/activities/notification/NotificationPublisher.java
> +        Notification notification = intent.getParcelableExtra("notification");
Ok, Will do

2017-03-04 14:21 UTC, Mathreyu commented on todoapp/TODOapp/app/src/main/java/com/nearsoft/androidschool/todoapp/activities/detail/DetailActivity.java
> +        notificationIntent.putExtra("notification id", 1);
change done :D

2017-03-04 14:21 UTC, Mathreyu commented on todoapp/TODOapp/app/src/main/java/com/nearsoft/androidschool/todoapp/activities/detail/DetailActivity.java
> +        notificationIntent.putExtra("notification", notification);
change done :D

2017-03-04 14:21 UTC, Mathreyu commented on todoapp/TODOapp/app/src/main/java/com/nearsoft/androidschool/todoapp/activities/notification/NotificationPublisher.java
> +        int id = intent.getIntExtra("notification-id", 0);
change done :D

2017-03-05 00:33 UTC, merged